// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/digitalocean.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IacProviderConfig is the typed configuration for the "iac.provider" module.
// It corresponds to the config map accepted by DOProvider.Initialize.
type IacProviderConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is the DigitalOcean personal access token (required).
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// region is the default DigitalOcean region slug (e.g. "nyc3").
	// Defaults to "nyc3" when empty.
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// spaces_access_key is the DO Spaces access key for object-storage operations.
	// Required only when the infra.storage resource type is used.
	SpacesAccessKey string `protobuf:"bytes,3,opt,name=spaces_access_key,json=spacesAccessKey,proto3" json:"spaces_access_key,omitempty"`
	// spaces_secret_key is the DO Spaces secret key for object-storage operations.
	// Required only when the infra.storage resource type is used.
	SpacesSecretKey string `protobuf:"bytes,4,opt,name=spaces_secret_key,json=spacesSecretKey,proto3" json:"spaces_secret_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IacProviderConfig) Reset() {
	*x = IacProviderConfig{}
	mi := &file_proto_digitalocean_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IacProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IacProviderConfig) ProtoMessage() {}

func (x *IacProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_digitalocean_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IacProviderConfig.ProtoReflect.Descriptor instead.
func (*IacProviderConfig) Descriptor() ([]byte, []int) {
	return file_proto_digitalocean_proto_rawDescGZIP(), []int{0}
}

func (x *IacProviderConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IacProviderConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *IacProviderConfig) GetSpacesAccessKey() string {
	if x != nil {
		return x.SpacesAccessKey
	}
	return ""
}

func (x *IacProviderConfig) GetSpacesSecretKey() string {
	if x != nil {
		return x.SpacesSecretKey
	}
	return ""
}

var File_proto_digitalocean_proto protoreflect.FileDescriptor

const file_proto_digitalocean_proto_rawDesc = "" +
	"\n" +
	"\x18proto/digitalocean.proto\x12\x1dworkflow.plugins.digitalocean\"\x99\x01\n" +
	"\x11IacProviderConfig\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12*\n" +
	"\x11spaces_access_key\x18\x03 \x01(\tR\x0fspacesAccessKey\x12*\n" +
	"\x11spaces_secret_key\x18\x04 \x01(\tR\x0fspacesSecretKeyB;Z9github.com/GoCodeAlone/workflow-plugin-digitalocean/protob\x06proto3"

var (
	file_proto_digitalocean_proto_rawDescOnce sync.Once
	file_proto_digitalocean_proto_rawDescData []byte
)

func file_proto_digitalocean_proto_rawDescGZIP() []byte {
	file_proto_digitalocean_proto_rawDescOnce.Do(func() {
		file_proto_digitalocean_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_digitalocean_proto_rawDesc), len(file_proto_digitalocean_proto_rawDesc)))
	})
	return file_proto_digitalocean_proto_rawDescData
}

var file_proto_digitalocean_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_digitalocean_proto_goTypes = []any{
	(*IacProviderConfig)(nil), // 0: workflow.plugins.digitalocean.IacProviderConfig
}
var file_proto_digitalocean_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_digitalocean_proto_init() }
func file_proto_digitalocean_proto_init() {
	if File_proto_digitalocean_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_digitalocean_proto_rawDesc), len(file_proto_digitalocean_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_digitalocean_proto_goTypes,
		DependencyIndexes: file_proto_digitalocean_proto_depIdxs,
		MessageInfos:      file_proto_digitalocean_proto_msgTypes,
	}.Build()
	File_proto_digitalocean_proto = out.File
	file_proto_digitalocean_proto_goTypes = nil
	file_proto_digitalocean_proto_depIdxs = nil
}
